version: "3.8"

services:
  bff:
    build:
      context: ./bff-service
      dockerfile: Dockerfile-local
    container_name: bff
    ports:
      - "${BFF_SERVICE_PORT}:${BFF_SERVICE_PORT}"
    environment:
      - BFF_SERVICE_PORT=${BFF_SERVICE_PORT}
    depends_on:
      - db
    networks:
      - nodejs_msa_network

  payment:
    build:
      context: ./payment-service
      dockerfile: Dockerfile-local
    container_name: payment
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    environment:
      - PAYMENT_SERVICE_PORT=${PAYMENT_SERVICE_PORT}
      - DATABASE_URL=${PAYMENT_DB_URL}
    depends_on:
      - db
    networks:
      - nodejs_msa_network

  listing:
    build:
      context: ./listing-service
      dockerfile: Dockerfile-local
    container_name: listing
    ports:
      - "${LISTING_SERVICE_PORT}:${LISTING_SERVICE_PORT}"
    environment:
      - LISTING_SERVICE_PORT=${LISTING_SERVICE_PORT}
      - DATABASE_URL=${LISTING_DB_URL}
    depends_on:
      - db
    networks:
      - nodejs_msa_network

  reservation:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile-local
    container_name: reservation
    ports:
      - "${RESERVATION_SERVICE_PORT}:${RESERVATION_SERVICE_PORT}"
    environment:
      - RESERVATION_SERVICE_PORT=${RESERVATION_SERVICE_PORT}
      - DATABASE_URL=${RESERVATION_DB_URL}
    depends_on:
      - db
    networks:
      - nodejs_msa_network

  homefront:
    build:
      context: ./homefront
      dockerfile: Dockerfile
    container_name: homefront
    ports:
      - "${HOMEFRONT_PORT}:${HOMEFRONT_PORT}"
    depends_on:
      - bff
    networks:
      - nodejs_msa_network

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    networks:
      - nodejs_msa_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks:
      - nodejs_msa_network
    ports:
      - 22181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    build: kafka
    networks:
      - nodejs_msa_network
    depends_on:
      - zookeeper
    ports:
      - 29093:29093
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:29093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:29093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      

  kafka_ui:
    container_name: kafka_ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - nodejs_msa_network
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092

volumes:
  postgres_data:

networks:
  nodejs_msa_network:
    driver: bridge
