FROM node:18-alpine AS base
ENV NODE_ENV production

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json /app/
RUN npm ci --production

FROM gcr.io/distroless/nodejs18-debian11

WORKDIR /app
COPY --from=base /app/node_modules /app/node_modules

USER nonroot

CMD ["main.js"]
