name: Lint - Build - Test
description: Runs a composite step action

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install packages dependencies
      run: yarn --immutable
      shell: bash

    - name: Lint
      run: yarn workspaces foreach -vp run lint
      shell: bash

    - name: Build
      run: yarn workspaces foreach -vp run build
      shell: bash

    - name: Test
      run: yarn workspaces foreach -vp run test
      shell: bash
