// https://erd.dbdesigner.net/


Location {
	id integer pk increments
	name varchar
	description text
	firstPic varchar
	createdAt date def(CURRENT_TIMESTAMP)
	createdBy integer
	updatedAt date
	updatedBy integer
}

Room {
	id integer pk increments
	name varchar
	description text
	mainPic varchar
	hotelId integer *> Hotel.id
	capacity json
	createdAt date def(CURRENT_TIMESTAMP)
	createdBy integer
	updatedAt date
	updatedBy integer
}

Amenity {
	id integer pk increments
	name varchar
	description text
	createdAt date def(CURRENT_TIMESTAMP)
	createdBy integer
	updatedAt date
	updatedBy integer
}

RoomAmenity {
	id integer pk increments
	roomId integer *> Room.id
	amenityId integer *> Amenity.id
	createdAt date def(CURRENT_TIMESTAMP)
	createdBy integer
	updatedAt date
	updatedBy integer
}

Hotel {
	id integer pk increments
	hotelName varchar
	description text
	geolocation point
	mainPic varchar
	address varchar
	city varchar
	locationId integer *> Location.id
    createdAt date def(CURRENT_TIMESTAMP)
	createdBy integer
	updatedAt date
	updatedBy integer
}

PropertyImage {
	id integer pk increments
	imagePath varchar
	createdAt date def(CURRENT_TIMESTAMP)
	createdBy integer
	updatedAt date
	updatedBy integer
}

RoomPropertyImage {
	id integer pk increments
	roomId integer *> Room.id
	propertyImageId integer *> PropertyImage.id
    createdAt date def(CURRENT_TIMESTAMP)
	createdBy integer
	updatedAt date
	updatedBy integer
}

RoomBooking {
	id integer pk increments
	firstName varchar
	lastName varchar
	email varchar
	paymentCard text
	fromDate date
	toDate date
	price decimal
	roomId integer *> Room.id
}