// https://erd.dbdesigner.net/

listing {
	id integer pk def(as)
	name varchar
	description text
	firstPic varchar
	categoryId integer *> category.id
	capacity json
	createdAt date
	createdBy integer
	updatedAt date
	updatedBy integer
}

category {
	id integer pk increments
	name varchar
	description text
	firstPic varchar
	createdAt date
	createdBy integer
	updatedAt date
	updatedBy integer
}

