FROM quay.io/keycloak/keycloak:latest as builder

WORKDIR /opt/keycloak

ENV KC_FEATURES=account3,admin-fine-grained-authz,declarative-ui

COPY ./realm.json /opt/keycloak/data/import/realm.json

# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_HOSTNAME=localhost
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin

# --import-realm: import the realm.json file
# --verbose: enable verbose logging
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm", "--verbose"]

EXPOSE 8080