name: BE service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - be/**

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        id: build-image
        uses: ./.github/actions/build-image
        with:
          repository: nashtech-garage/nodejs-msa-be
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          willPush: false
          dockerfile: docker/be.Dockerfile
          workspace: nodejs-msa-be
          workspacePath: be
